name: Analyze

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run Git History Analyzer
        uses: BamaCharanChhandogi/git-analyzer@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
